services:
  - type: web
    name: milestone1-backend
    env: java
    plan: free
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/milestone1-0.0.1-SNAPSHOT.jar
    autoDeploy: true
    envVars:
      - key: JAVA_VERSION
        value: 17
